# Generated by Django 4.2.20 on 2025-04-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='ảtist',
            new_name='artist',
        ),
    ]
