# Generated by Django 4.2.20 on 2025-04-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_rename_ảtist_song_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.CharField(max_length=20),
        ),
    ]
