# Generated by Django 4.2.20 on 2025-04-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_song_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='file_path',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='image_path',
            new_name='image',
        ),
    ]
